name: Check & fix styling & Deployment

on: 
  push:
    branches:
      - main

jobs:
    pint:
        name: Run Pint before Deployment
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@main
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: '8.2'
            - name: Install dependencies
              run: composer install --no-interaction
            - name: Run Pint
              run: ./vendor/bin/pint
            - name: Commit changes
              uses: stefanzweifel/git-auto-commit-action@main
              with:
                  commit_message: Fix styling
    deploy:
      name: Deploy to Production
      runs-on: ubuntu-latest
      needs: pint
      steps:
        - name: Checkout Repository
          uses: actions/checkout@main
        - name: ssh into Dev Server
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            script: |
              cd /var/www/html/filament
              git pull
              composer install
              php artisan optimize:clear
              php artisan migrate
              php artisan optimize
              echo "Deploy successful"
